### PR TITLE
xIisLogging and xWebsite: Add Ensure property to LogCustomFields

### LINKED ISSUE #571: xIisLoggingCustomField - Able to remove or ensure absent?
Are we able to ensure certain custom fields are absent or remove all of the custom fields? This could be useful for rolling back configurations.

### PR DESCRIPTION
**Pull request by Clay10J**
#### Pull Request (PR) description
Added the Ensure property to log custom fields in xWebsite and fixed this property in xIisLogging

#### This Pull Request (PR) fixes the following issues
Fixes #571 / #572 by allowing removal of all custom fields (previously caused error).

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/576)

### CODE REVIEW

**Comment by Clay10J** [comment]
@johlju @regedit32 I am unsure of the error causing the build failure. Could you take a look at the updated code? Thanks!

**Comment by johlju** [comment]
We have renamed the resource, removing 'x', so please rebase this PR.

**Comment by johlju** [comment]
Looks like the unit test failed with an error unrelated to this change in this PR, I kicked off the failed tests again to verify 🤔

**Comment by johlju** [comment]
@Clay10J  I just merged a fix. Could you please rebase again?

**Review by johlju — APPROVED** [review]
This looks good, this is ready to merge after just one more change. :slightly_smiling_face:  Could we add examples (similar to the config for integ test) for both resource, both for absent and present (if it does not already exist)?

https://github.com/dsccommunity/WebAdministrationDsc/tree/main/source/Examples/Resources/IisLogging
https://github.com/dsccommunity/WebAdministrationDsc/tree/main/source/Examples/Resources/WebSite

> Reviewed 19 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/576#-:-NkxrZw3ENyVN-vTuzHI:b-nzo0pz)* status: all files reviewed, 3 unresolved discussions (waiting on @regedit32)

**Comment by johlju** [comment]
@Clay10J just one more change then this is ready for merge, se previous comment.

**Comment by johlju** [comment]
... and also for the Wiki docs to generate correctly.

**Comment by Clay10J** [comment]
Ah my bad. I'll get that fixed up

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/576#-:-Nl49KyEBarq-51T2pc5:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @regedit32)

**Pull request merged**
