### PR TITLE
WebConfigPropertyCollection: Allow deleting single item property collections, update examples, remove duplicate resource documentation

### LINKED ISSUE #379: xWebConfigPropertyCollection: support single property collection
I am trying to add a Server Variable to rewrite. In the C:\Windows\System32\inetsrv\config\applicationHost.config, the desired outcome looks like this:
```
<rewrite>
<allowedServerVariables>
<add name="RESPONSE_Server" />
</allowedServerVariables>
</rewrite>

```
I have a script that creates the variable:
`Add-WebConfigurationProperty -pspath $IISPath -filter "system.webServer/rewrite/allowedServerVariables" -name "." -value @{name="RESPONSE_Server"} 
`
So far, I can't figure out the way to do the same with xWebConfigProperty. This won't work:
```
xWebConfigProperty RESPONSE_Server
{
    Ensure = "Present"
    Filter = "system.webServer/rewrite/allowedServerVariables"
    WebsitePath = "MACHINE/WEBROOT/APPHOST"
    PropertyName = "."
    Value = "RESPONSE_Server"
}

```
I would need something of that sort:
`Value = @{name="RESPONSE_Server"}`
But there is no way to pass a hashtable into the Value parameter

### LINKED ISSUE #631: WebConfigPropertyCollection needs to allow null or empty strings for specific collection items like '/system.webServer/security/requestFiltering/hiddenSegments'
### Problem description

Test-DSCResource fails as there is NO PROPERTY for this collection, only values under the add segment

```  XML
   <requestFiltering>
       <...>
       <hiddenSegments applyToWebDAV="true">
            <add segment="web.config" />
            <add segment="bin" />
            <add segment="App_code" />
            <add segment="App_GlobalResources" />
            <add segment="App_LocalResources" />
            <add segment="App_WebReferences" />
            <add segment="App_Data" />
            <add segment="App_Browsers" />
            <add segment="appsettings.json" />
        </hiddenSegments>
    </requestFiltering>
```

### Verbose logs

```text
VERBOSE: [localhost]: LCM:  [ Start  Resource ]  [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments]                                                                                     VERBOSE: [localhost]: LCM:  [ Start  Test     ]  [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments]                                                                                     VERBOSE: [localhost]:                            [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments] Checking for the existence of property "@()" in collection item                     "hiddenSegments/add" with key "segment=appsettings.json" using filter "/system.webServer/security/requestFiltering"     located at "MACHINE/WEBROOT/APPHOST".                                                                                   VERBOSE: [localhost]:                            [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments] Property "@()" has not been found.                                                  VERBOSE: [localhost]: LCM:  [ End    Test     ]  [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments]  in 0.0090 seconds.                                                                 VERBOSE: [localhost]: LCM:  [ Start  Set      ]  [[WebConfigPropertyCollection]###localhost - Add           appsettings JSON to hiddensegments]
VERBOSE: [localhost]:                            [[WebConfigPropertyCollection]###localhost - Add appsettings JSON to hiddensegments] Checking for the existence of property "@()" in collection item "hiddenSegments/add" with key "segment=appsettings.json" using filter "/system.webServer/security/requestFiltering" located at "MACHINE/WEBROOT/APPHOST".
VERBOSE: [localhost]:                            [[WebConfigPropertyCollection]###localhost - Add appsettings JSON to hiddensegments] Collection item "hiddenSegments/add" with key "segment=appsettings.json" exists, editing property "@()". WARNING: [localhost]:                            [[WebConfigPropertyCollection]###localhost - Add appsettings JSON to hiddensegments] Property @() is not found on /system.webServer/security/requestFiltering/hiddenSegments/add[@segment='appsettings.json'].
VERBOSE: [localhost]: LCM:  [ End    Set      ]  [[WebConfigPropertyCollection]###localhost - Add appsettings JSON to hiddensegments]  in 1.0620 seconds.
VERBOSE: [localhost]: LCM:  [ End    Resource ]  [[WebConfigPropertyCollection]###localhost - Add appsettings JSON to hiddensegments]
VERBOSE: [localhost]: LCM:  [ End    Set      ]
VERBOSE: [localhost]: LCM:  [ End    Set      ]    in  1.5670 seconds.
```

### DSC configuration

```powershell
WebConfigPropertyCollection "###$($NodeName) - Add appsettings JSON to hiddensegments"
        {
            WebsitePath       = 'MACHINE/WEBROOT/APPHOST'
            Filter            = '/system.webServer/security/requestFiltering'
            CollectionName    = 'hiddenSegments'
            ItemName          = 'add'
            ItemKeyName       = 'segment'
            ItemKeyValue      = 'appsettings.json'
            ItemPropertyName  = '@()'
            ItemPropertyValue = '@()'
            Ensure            = 'Present'
        }
```

### Suggested solution

  Allow both **ItemPropertyName** and **ItemPropertyValue** _to be empty_ if required or have some other _bypass variable_. Without this capability the **hiddenSegments** entry will always return false and DSC config will fail.

### Operating system the target node is running

```text
Windows Server 2022
```

### PowerShell version and build the target node is running

```text
PS E:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.1850
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1850
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### WebAdministrationDsc version

```text
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   4.1.0      WebAdministrationDsc
```

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

Add support for single item property value collections - add is already supported with the correct syntax, so have updated examples & added 'delete' support.

(NB 'Updating' a single item property value collection is pretty meaningless as there's nothing relevant to 'update' - you can only add or delete).

Also removing the duplicated resource documentation under README.md. Most resources solely rely on the Wiki, which should surely be the 'single source of truth' for resource documentation now, like for other modules?

#### This Pull Request (PR) fixes the following issues

- Fixes #379
- Fixes #631

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/644)

### CODE REVIEW

**Review by dan-hughes — COMMENTED** [review]
:lgtm:

@johlju.

> Reviewed 3 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/644#-:-OAviBfMB8542kbzwS9s:bwdpzjf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Comment by dan-hughes** [comment]
One thing I've just thought about @Borgquite, can you add a link in the README to the Wiki. e.g. 

'The resource examples are also available in the [WebAdministrationDsc Wiki](https://github.com/dsccommunity/WebAdministrationDsc/wiki).'

**Comment by Borgquite** [comment]
@dan-hughes Already there?

https://github.com/dsccommunity/WebAdministrationDsc/blob/c3efe116a1ab02fa49b354f5c72e5cccf31110e9/README.md?plain=1#L42

**Comment by dan-hughes** [comment]
> @dan-hughes Already there?
> 
> https://github.com/dsccommunity/WebAdministrationDsc/blob/c3efe116a1ab02fa49b354f5c72e5cccf31110e9/README.md?plain=1#L42

So it is. I went to the bottom, saw the examples and didn't look very hard after that!

Could do with cleaning up the two examples headings. 

Beat me to it!

Should be good now.

**Comment by Borgquite** [comment]
@dan-hughes Ah, I see what's happened - there are *two* Examples sections in the README file, one with, one without.

I've just merged them

**Pull request merged**
