### PR TITLE
BREAKING CHANGE: xWebAdministration renamed to WebAdministrationDsc: Renamed all DSCResources, Examples, Modules and Tests where applicable

### LINKED ISSUE #213: Rename this resource module to WebAdministrationDsc
Looking for any and all feedback on the first release of [WebAdministrationDsc](https://github.com/PowerShell/xWebAdministration/tree/WebAdministrationDsc)!

### LINKED ISSUE #363: xIisHandler: Remove deprecated resource
New resource 'xWebApplicationHandler' will replace the 'xIisHandler' resource

### LINKED ISSUE #369: Remove deprecated xWebConfigKeyValue resource in future release
#330 replaces the xWebConfigKeyValue resource with new resources that provide more comprehensive functionality. Suggest the xWebConfigKeyValue resource is removed in a future release.

### PR DESCRIPTION
**Pull request by nickgw**
#### Pull Request (PR) description
xWebAdministration renamed to WebAdministrationDsc

#### This Pull Request (PR) fixes the following issues

- Fixes #213
- Fixes #369 
- Fixes #363 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/601)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 139 of 144 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601)* status: 139 of 144 files reviewed, 21 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`azure-pipelines.yml` line 160 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3Er4eQ3VyTZirzEnpg:-N3Er4eQ3VyTZirzEnph:b-4uji9t) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/03f8b9df0196bf65d652f6f7e47a8fe4b2c8db85/azure-pipelines.yml#L160)):*
> ```YAML
>         displayName: 'Integration (Windows Server 2019)'
>         pool:
>           vmImage: 'windows-2019'
> ```

Very strange that this does not work since, as I saw now, the integration tests run an  Windows Server 2019 before.
I'm not sure why this does not work anymore, something must have changed on the build worker since last time the integration tests ran. I will try to push a blank PR to see if that fails too.



_Code quote:_
```YAML
'windows-2019'
```
___
*[`source/DSCResources/DSC_WebConfigPropertyCollection/DSC_WebConfigPropertyCollection.schema.mof` line 2 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2eC5CB_KFtWjzmcA:-N3F2eC5CB_KFtWjzmcB:btm3e2x) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/03f8b9df0196bf65d652f6f7e47a8fe4b2c8db85/source/DSCResources/DSC_WebConfigPropertyCollection/DSC_WebConfigPropertyCollection.schema.mof#L2)):*
> ```
> [ClassVersion("1.0.0.0"), FriendlyName("WebConfigPropertyCollection")]
> class Dsc_WebConfigPropertyCollection : OMI_BaseResource
> ```

We should have this in upper-case `DSC_`



_Code quote:_
```
Dsc_
```
___
*[`source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1` line 33 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F1rv-CMjwwYVZWxyJ:-N3F1rv-CMjwwYVZWxyK:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1#L33)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1` line 121 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F1y-H9hZ6FBoxm4r2:-N3F1y-H9hZ6FBoxm4r3:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1#L121)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1` line 323 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F1zA_BNRkf-kHtO1Z:-N3F1zA_BNRkf-kHtO1_:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1#L323)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1` line 243 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2QmP0tSoRonTGKxv:-N3F2QmP0tSoRonTGKxw:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L243)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
 Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1` line 520 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2RmuAXmWwNxap-GV:-N3F2RmuAXmWwNxap-GW:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L520)):*
> ```PowerShell
>     }
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1` line 934 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2Ss2A4OFdJwuysQY:-N3F2Ss2A4OFdJwuysQZ:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L934)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
 Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1` line 27 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2W1NCxKGB4lRBi2_:-N3F2W1O9OJnwMlBfwhq:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L27)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1` line 64 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2X8kB6cMd5U1tQ6g:-N3F2X8kB6cMd5U1tQ6h:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L64)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1` line 99 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2YJS-XwLYx6X18y8:-N3F2YJS-XwLYx6X18y9:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L99)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1` line 33 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2n6613Fl5u2omP5c:-N3F2n6613Fl5u2omP5d:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1#L33)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1` line 227 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2nxz5hCtEESOLjs1:-N3F2nxz5hCtEESOLjs2:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1#L227)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1` line 794 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F2p5ABxf_plnv3tnr:-N3F2p5ABxf_plnv3tns:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1#L794)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1` line 27 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F33B8AJuQdVAYOhMc:-N3F33B95jxaL-6eATRj:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1#L27)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1` line 80 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F341K1DVD6Myy19uz:-N3F341K1DVD6Myy19v-:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1#L80)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1` line 124 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F35Zr7OqQS6Wnq_g0:-N3F35Zr7OqQS6Wnq_g1:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1#L124)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1` line 38 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F38x56wKuzSIXUTOq:-N3F38x56wKuzSIXUTOr:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1#L38)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1` line 98 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F3A1uCWGAZEUYDaiy:-N3F3A1uCWGAZEUYDaiz:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1#L98)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1` line 175 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F3Az2-8_7KTcHw_ya:-N3F3Az2-8_7KTcHw_yb:b-qd3od6) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/673d20f7a73d2e6bfdd0715a5628bd7ffa708d5f/source/DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1#L175)):*
> ```PowerShell
>     )
> 
>     Assert-Module
> ```

Why did we have to remove this?



_Code quote:_
```PowerShell
Assert-Module
```
___
*[`tests/Unit/DSC_IISFeatureDelegation.Tests.ps1` line 66 at r2](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3F6rPv2TplmSq9lR8T:-N3F6rPv2TplmSq9lR8U:bzfbd8w) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/03f8b9df0196bf65d652f6f7e47a8fe4b2c8db85/tests/Unit/DSC_IISFeatureDelegation.Tests.ps1#L66)):*
> ```PowerShell
>         Describe 'DSC_IisFeatureDelegation\Get-TargetResource' {
>             BeforeAll {
>                 Mock -CommandName Assert-Module -MockWith {}
> ```

We do not need this if we mock nothing, it is enough with `Mock -CommandName Assert-Module`. Throughout the tests inb all files.



_Code quote:_
```PowerShell
 -MockWith {}
```

**Comment by johlju** [comment]
I'm pushing new pipelines files in PR https://github.com/dsccommunity/xWebAdministration/pull/603. That PR passes integration tests. I will switch to the same build workers as in this PR inb another PR just to rule build workers out.

**Comment by johlju** [comment]
So I have switched to the new build workers and the pipeline stil works. I pushed a few files to get wiki documentation updated (README.md file in each resource folder), they need renaming too now.

**Comment by johlju** [comment]
If you rebase this PR now, let us see what fails and work from there, if something fails then now we can be certain that it is the code changes that we need to look into, not the build workers having issues. 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
Thanks for correcting my mistakes. :slightly_smiling_face:  :bowing_man: 

> Reviewed 20 of 42 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-:-N3KtwIR51VOJTP2hU8w:b-z7ptbz)* status: 135 of 161 files reviewed, 16 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`build.yaml` line 64 at r3](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3Ksds53YJaYQhCxFPs:-N3Ksds53YJaYQhCxFPt:brjrp2l) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/4e3087a40251f7a10e82e1e1454896d37c924122/build.yaml#L64)):*
> ```YAML
> Pester:
>   OutputFormat: NUnitXML
>   ExcludeFromCodeCoverage:
> ```

We should change this to:



_Suggestion:_
```YAML
  ExcludeFromCodeCoverage:
    - Modules/DscResource.Common
```
___
*[`build.yaml` line 78 at r3](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3KsV6N7Ofjl0k7i5s1:-N3KsV6N7Ofjl0k7i5s2:brjrp2l) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/4e3087a40251f7a10e82e1e1454896d37c924122/build.yaml#L78)):*
> ```YAML
>   ExcludeSourceFile:
>     - output
>   ExcludeModuleFile:
> ```

We should change this to:



_Suggestion:_
```YAML
  ExcludeModuleFile:
    - Modules/DscResource.Common
```
___
*[`codecov.yml` line 3 at r4](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3KtBvwD8MfiiPd4fQ8:-N3KtBvxEa3OiyvZCPCq:b4kfkun) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/df669ce662ff3e03ad1268498086204f34cb8717/codecov.yml#L3)):*
> ```YAML
> codecov:
>   require_ci_to_pass: no
>   # master should be the baseline for reporting
> ```

Should be:



_Suggestion:_
```YAML
main
```
___
*[`README.md` line 3 at r4](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3KtP9I3GZtRjsjFZ89:-N3KtP9I3GZtRjsjFZ8A:bdhjuni) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/334575ac032f2b04f98bdaed1149f904d5d35899/README.md#L3)):*
> ```Markdown
> # xWebAdministration
> 
> This module contains DSC resources for the management and
> ```

This was removed:



_Code quote:_
```Markdown
This module contains DSC resources for the management and
configuration of Microsoft Internet Information Services (IIS).
```
___
*[`README.md` line 8 at r4](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3KtSrnArLlzZxcunet:-N3KtSrnArLlzZxcuneu:b-7wigk7) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/334575ac032f2b04f98bdaed1149f904d5d35899/README.md#L8)):*
> ```Markdown
> [Build Status](https://dev.azure.com/dsccommunity/xWebAdministration/_build/latest?definitionId=7&branchName=main)
> Azure DevOps coverage (branch)
> [codecov](https://codecov.io/gh/dsccommunity/xWebAdministration)
> ```

This was removed (should also be renamed correctly)



_Code quote:_
```Markdown
[![codecov](https://codecov.io/gh/dsccommunity/xWebAdministration/branch/main/graph/badge.svg)](https://codecov.io/gh/dsccommunity/xWebAdministration)
```

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 144 files at r1, 1 of 1 files at r2, 22 of 42 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @nickgw)

___
*[`tests/TestHelper/CommonTestHelper.psm1` line 238 at r4](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3KwQKz8dAle57xxeHi:-N3KwQKz8dAle57xxeHj:bboi6oz) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/df669ce662ff3e03ad1268498086204f34cb8717/tests/TestHelper/CommonTestHelper.psm1#L238)):*
> ```PowerShell
> #>
> function New-SelfSignedCertificateEx {
>     [OutputType('[System.Security.Cryptography.X509Certificates.X509Certificate2]')]
> ```

We should not need this as we use the command from the module PSPKI. :thinking:  See https://github.com/dsccommunity/xWebAdministration/blob/334575ac032f2b04f98bdaed1149f904d5d35899/tests/Unit/xWebAdministration.Common.Tests.ps1#L27

I added it in one of the PR's I pused yesterday.



_Code quote:_
```PowerShell
New-SelfSignedCertificateEx
```

**Comment by johlju** [comment]
@nickgw it seems this row fails in the integration tests:

https://github.com/dsccommunity/xWebAdministration/blob/df669ce662ff3e03ad1268498086204f34cb8717/tests/Integration/DSC_WebApplication.Integration.Tests.ps1#L102

I'm think, can it be that we run the integration tests to fast. Can we test adding `Start-Sleep -Seconds 5` before running the command? If that doesn't work I suggest comment that test, the create an issue to track it and we move on. Let us in that case fix it in another PR. What do you think?

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601)* status: all files reviewed, 1 unresolved discussion (waiting on @nickgw)

___
*[`README.md` line 8 at r5](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3L-oGu8QIMpsGK3FY-:-N3L-oGu8QIMpsGK3FY0:b4kfkun) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/5723cc8ac1b36bc3752736d77b16828474902121/README.md#L8)):*
> ```Markdown
> Azure DevOps coverage (branch)
> [Azure DevOps tests](https://dsccommunity.visualstudio.com/WebAdministrationDsc/_test/analytics?definitionId=7&contextType=build)
> [codecov](https://codecov.io/gh/dsccommunity/xWebAdministration)
> ```

Should be:



_Suggestion:_
```Markdown
WebAdministrationDsc
```

**Comment by johlju** [comment]
It is like the Get-TargetResource function throws an error or returns some unexpected value that Get-TargetResource does not like. 🤔

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601)* status: 160 of 161 files reviewed, 2 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`tests/Integration/DSC_WebApplication.Integration.Tests.ps1` line 74 at r7](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-N3LL5Au9Q5PY8t-psaG:-N3LL5Au9Q5PY8t-psaH:bs849ty) ([raw file](https://github.com/dsccommunity/xwebadministration/blob/f16a61ecc78f52f88f0e384b9b48005b789a87e9/tests/Integration/DSC_WebApplication.Integration.Tests.ps1#L74)):*
> ```PowerShell
>         It 'Should compile without throwing' {
>             {
>                 Invoke-Expression -Command "$($script:dscResourceName)_Present -ConfigurationData `$DSCConfig -OutputPath `$TestDrive"
> ```

This should be `$configData` now?



_Code quote:_
```PowerShell
$DSCConfig
```

**Comment by johlju** [comment]
Now it fails with the previous error again. Looking at the tests thay run for xWeb I see the do run in a different order now... It might be something a previous test added that made the test, by luck, work previously. 🤔

**Comment by johlju** [comment]
I think the integration test need to be refactored, like you tried too. But we can do that in another PR. I happy to comment put the test and make an issue for it to fix, by someone, in another PR.

**Comment by nickgw** [comment]
> It is like the Get-TargetResource function throws an error or returns some unexpected value that Get-DscConfiguration does not like. 🤔

I'm creating an issue now. It baffles me that this worked in your PR, but is failing in mine.

> I think the integration test need to be refactored, like you tried too. But we can do that in another PR. I happy to comment out the test and make an issue for it to be fixed, by someone, in another PR.

Created this for the failing integration test: https://github.com/dsccommunity/xWebAdministration/issues/606

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/601#-:-N3Vh2bs8LsT1xkn-nVR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)

**Comment by johlju** [comment]
Awesome work @nickgw! This PR is ready, I will rename this repo as soon as I have a chance.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/601#-:-N3eYv-BAXaRgKBMzlUg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)

**Comment by johlju** [comment]
Waiting for the API key to be update on the pipeline so we can merge this.

**Pull request merged**
