### PR TITLE
xWebConfigPropertyCollection: Escape curly braces to allow URLRewrite variables to work.

### LINKED ISSUE #430: xWebConfigPropertyCollection: braces not accepted in ItemKeyValue
#### Details of the scenario you tried and the problem that is occurring

I'm trying to add a URL Rewrite condition that has the ItemKeyValue "{HTTPS}".  When applying this via DSC, I get this error logged to the DSC Operational log:

`MIResult: 1
Error Message: The PowerShell DSC resource '[xWebConfigPropertyCollection]HSTS_Condition' with SourceInfo '::688::9::xWebConfigPropertyCollection' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
Message ID: NonTerminatingErrorFromProvider
Error Category: 7
Error Code: 1
Error Type: MI`

Troubleshooting and trying to manually add this using the `Add-WebConfigurationProperty` cmdlet, the condition is not fully added.  Example:
```powershell
add-WebConfigurationProperty -pspath "MACHINE/WEBROOT/APPHOST" -Filter "system.webServer/rewrite/outboundRules/rule[@name='Add Strict-Transport-Security when HTTPS']/conditions" -name "." -value @{name='{HTTPS}'}
```
results in this being added to the applicationHost.config:
```xml
<conditions>
<add />
</conditions>
```

Running the same DSC resource and powershell cmdlet without the { } around the HTTPS results in the condition being added correctly - obviously missing the { } braces. 

I'm not sure if this is an escaping issue to do with the braces that I'm missing, or if there is something in the background that is unable to handle them correctly. 
If it's a simple escaping issue, any help pointing me in the right direction is appreciated. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
xWebConfigPropertyCollection HSTS_Condition {
            WebsitePath = 'MACHINE/WEBROOT/APPHOST'
            Filter      = "system.webServer/rewrite/outboundRules/rule[@name='Add Strict-Transport-Security when HTTPS']"
            CollectionName = 'conditions'
            ItemName = 'add'
            ItemKeyName = 'input'
            ItemKeyValue = "{HTTPS}"
            ItemPropertyName = 'pattern'
            ItemPropertyValue = 'on'
            Ensure = 'Present'
            DependsOn = '[xWebConfigPropertyCollection]OutboundRuleName_HSTS'
        }
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19376.amd64fre.winblue_ltsb_escrow.190520-1700
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```
PowerShell      WebApplicationHandler     xWebAdministration             2.6.0.0
PowerShell      xIisFeatureDelegation     xWebAdministration             2.6.0.0
PowerShell      xIisHandler               xWebAdministration             2.6.0.0
PowerShell      xIisLogging               xWebAdministration             2.6.0.0
PowerShell      xIisMimeTypeMapping       xWebAdministration             2.6.0.0
PowerShell      xIisModule                xWebAdministration             2.6.0.0
PowerShell      xSSLSettings              xWebAdministration             2.6.0.0
PowerShell      xWebApplication           xWebAdministration             2.6.0.0
PowerShell      xWebAppPool               xWebAdministration             2.6.0.0
PowerShell      xWebAppPoolDefaults       xWebAdministration             2.6.0.0
PowerShell      xWebConfigKeyValue        xWebAdministration             2.6.0.0
PowerShell      xWebConfigProperty        xWebAdministration             2.6.0.0
PowerShell      xWebConfigPropertyColl... xWebAdministration             2.6.0.0
PowerShell      xWebsite                  xWebAdministration             2.6.0.0
PowerShell      xWebSiteDefaults          xWebAdministration             2.6.0.0
PowerShell      xWebVirtualDirectory      xWebAdministration             2.6.0.0
```

### PR DESCRIPTION
**Pull request by a-mcf**
#### Pull Request (PR) description
Fix issue #430 by doubling up curly braces enabling the use of URLRewrite variables.

#### This Pull Request (PR) fixes the following issues
- Fixes #430
#### Task list
- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/599)

### CODE REVIEW

**Comment by a-mcf** [comment]
Note that the test failures here aren't related to anything I changed. I suspect the current module  may have issues with it's tests.

**Comment by johlju** [comment]
We have renamed the resource, removeing 'x', so please rebase this PR.

**Comment by johlju** [comment]
We have renamed the resource, removing 'x', so please rebase this PR.

**Comment by a-mcf** [comment]
Done.

**Comment by johlju** [comment]
This PR now proposes to change 177 files which let me think something went wrong during rebase. Please take a look at it, and let me know if I can be of assistance.

**Comment by a-mcf** [comment]
@johlju - I'm killing this in favor of https://github.com/dsccommunity/WebAdministrationDsc/pull/612/files. The branch looked ok when I looked at it locally and on my github page. I just branched off of it and pushed a new PR and its only showing two files modified.

I wish I knew what happened but at this point am going to shrug my shoulders and move on.

**Pull request closed without merging**
