### PR TITLE
xWebfarm DSCResource

### PR DESCRIPTION
**Pull request by xunilrj**
This PR is for the xWebfarm (http://www.iis.net/downloads/microsoft/web-farm-framework) DSC resource. The resource tries to be as identical to the XML as possible.

Example:
https://github.com/xunilrj/xWebAdministration/blob/dev/Examples/Sample_xWebfarm_NewWebfarm.ps1

To understand all the functionalities implemented I suggest to look to the tests.

https://github.com/xunilrj/xWebAdministration/blob/dev/Tests/Unit/MSFT_xWebfarm.tests.ps1

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/103)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Sorry I'm just now having time to review this.  Couple of things.  Please update the resource to follow all [StyleGuidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md). Specifically curly braces get their own line, and all functions should be noun-verb (and preferably with an approved verb).

Please make use of LocalizedData, specifically move all of the verbose message strings to it, it allows localized a central location for the strings, and allows targeting loc changes if we ever decide to make them.

I would also suggest using the following style for verbose messages:

````powershell
Write-Verbose -Message ($LocalizedData.VerboseSetTargetUpdatedApplicationPool -f $Name, $ApplicationPool)
````

For Error Messages please use the `New-TerminatingError` from the `Helper.psm1` module in the root of the DSCResource Folder


While the testing you have is pretty good, would it be possible for you to write some integration tests as well?

---

Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1, line 35 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhgSP4Xo2cZUK96P8N:-KEhgSP4Xo2cZUK96P8O:882122747) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1#L35)):*
I'm not actually sure this works in DSC, and given that we're calling it from a dsc config I'm not sure I see the value of having it.

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1, line 255 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhgc9Z9RRRjvzlm2ar:-KEhgc9Z9RRRjvzlm2as:442454203) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1#L255)):*
I would suggest avoiding declartions such as these, instead I would suggest language like "More then one webfarm found, please investigate the config file located at $location"

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1, line 263 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhgvVtIpRe2C_o0RmE:-KEhgvVtIpRe2C_o0RmF:-1965542805) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1#L263)):*
Please use the param construct

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1, line 316 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhh32gpqscBeHgB0IK:-KEhh32gpqscBeHgB0IL:2058078206) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1#L316)):*
Please put all parameters on their own lines.

ie:
````powershell
param 
(
    [string] $ConfigPath,
    [xml] $XML
)
````

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1, line 327 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhE3TW30afHrlBuDU:-KEhhE3TW30afHrlBuDV:633383888) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.psm1#L327)):*
All files must have new lines at the end of them, please adjust.

---

*[DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.schema.mof, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhHT-BySUupC6EOrB:-KEhhHT-BySUupC6EOrC:-1518421829) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/DSCResources/MSFT_xWebfarm/MSFT_xWebfarm.schema.mof#L4)):*
Best practice would be to add Description fields here.

---

*[Examples/Sample_xWebfarm_NewWebfarm.ps1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhM5kzrUXZCIjHUDk:-KEhhM5kzrUXZCIjHUDl:767681649) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Examples/Sample_xWebfarm_NewWebfarm.ps1#L1)):*
I'm not sure this is necessary here.

---

*[Examples/Sample_xWebfarm_NewWebfarm.ps1, line 3 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhNSmQA3_Z20E_8Q4:-KEhhNSmQA3_Z20E_8Q5:266745838) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Examples/Sample_xWebfarm_NewWebfarm.ps1#L3)):*
This shouldn't be ncessary.

---

*[Examples/Sample_xWebfarm_NewWebfarm.ps1, line 31 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhRWxhcTBS6boMuS-:-KEhhRWxhcTBS6boMuS0:-446002252) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Examples/Sample_xWebfarm_NewWebfarm.ps1#L31)):*
Typically in our examples we do not actually configure the machine, we just provide the configuration listed above. Please use our other examples as guidelines.

---

*[Tests/Unit/MSFT_xWebfarm.tests.ps1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhcUe-awlcDdRd_00:-KEhhcUe-awlcDdRd_01:1730225004) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Tests/Unit/MSFT_xWebfarm.tests.ps1#L1)):*
Please remove these comments as they are not necessary once the template has been copied.

---

*[Tests/Unit/MSFT_xWebfarm.tests.ps1, line 15 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhgbTFk_duAt3-Fg0:-KEhhgbTFk_duAt3-Fg1:584691171) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Tests/Unit/MSFT_xWebfarm.tests.ps1#L15)):*
You can remove these comments too.

---

*[Tests/Unit/MSFT_xWebfarm.tests.ps1, line 675 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhht5S4TwHzj2RP-Pp:-KEhht5S4TwHzj2RP-Pq:-283595222) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Tests/Unit/MSFT_xWebfarm.tests.ps1#L675)):*
Please test your internal functions as well.

---

*[Tests/Unit/MSFT_xWebfarm.tests.ps1, line 687 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-KEhhvv6nxK7uF_vNkg7:-KEhhvv6nxK7uF_vNkg8:427317115) ([raw file](https://github.com/powershell/xwebadministration/blob/dc3b265d260890b333a72464d8caffa2ea8912a7/Tests/Unit/MSFT_xWebfarm.tests.ps1#L687)):*
New line here please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/103#-:-KEhfINhIx6G7ITBG6vM:-1322586807)*

**Comment by xunilrj** [comment]
Off course. I will make the changes. :)

**Comment by tysonjhayes** [comment]
Howdy, are you still working on this?

**Comment by tysonjhayes** [comment]
Hi, haven't heard from you in a while, as it's been 18 days since I last pinged you and I haven't seen any activity I'm going to go ahead and close this. Please feel free to reopen it once you've made some more changes.

Thanks!

**Comment by johlju** [comment]
I will reopen this and mark this as abandoned so someone else can continue this work, since this is work on an open issue.

**Pull request closed without merging**
