### PR TITLE
xWebSite: Choose cert with greatest validity

### LINKED ISSUE #578: xWebsite: finds certificates with no private key to bind to SSL.  Doesn't choose a cert with most available time.
#### Details of the scenario you tried and the problem that is occurring
  Using xWebSite to deploy SSL certificates using a subject name.  When multiple certificates exist with the same subject name, xwebsite chooses one at random, not one with the most useable time.  When multiple certificates exist with the same subject name, and one doesn't have a private key, the code may pick that cert and attempt to bind it to SSL, causing an error.

#### Verbose logs showing the problem
NA to share for security reasons

#### Suggested solution to the issue
Replace line 1476 with:
$Certificate = Find-Certificate @FindCertificateSplat | Where-Object {$_.HasPrivateKey -eq $true} | Sort-Object -Property NotAfter -Descending | Select-Object -First 1

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        xWebSite BindCert {
            Ensure = 'Present'
            Name = 'Default Web Site'
            BindingInfo     = @(
                MSFT_xWebBindingInformation
                {
                    Protocol              = 'HTTPS'
                    Port                  = 443
                    CertificateSubject    = 'CN=DuplicateSubject'
                    CertificateStoreName  = 'MY'
                }
            )
        }
```

#### Version of the DSC module that was used
3.1.1.1

### PR DESCRIPTION
**Pull request by ThomasHughesIV**
#### Task list

- [x ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/579)

### CODE REVIEW

**Comment by ThomasHughesIV** [comment]
Wow, is pester updated or something?  I cannot see how this failed so badly in build when changing one line of code with Where-Object statements

**Comment by johlju** [comment]
Yes, Pester 5 was released so we need to pin Pester to 4.10.1 here

https://github.com/dsccommunity/xWebAdministration/blob/c7c81dcdca4102b5e06f0ffed16b35d1b7f6c07b/RequiredModules.psd1#L11

**Comment by ThomasHughesIV** [comment]
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/xwebadministration/579)_ status: all files reviewed, 1 unresolved discussion (waiting on @ThomasHughesIV)
> 
> _[a discussion](https://reviewable.io/reviews/dsccommunity/xwebadministration/579#-MBVQphm8hPNG3Dvp3e6:-MBVQphm8hPNG3Dvp3e7:baunorp) (no related file):_
> Can you please add a unit test (or change an existing) so that the correct certificate is chosen?
> 
> https://github.com/dsccommunity/xWebAdministration/blob/c7c81dcdca4102b5e06f0ffed16b35d1b7f6c07b/tests/Unit/MSFT_xWebsite.Tests.ps1#L2273

Yes, I can do that.  I think.  I'm still new to all of this.

**Comment by johlju** [comment]
Ping me if I can help in some way.

**Comment by ThomasHughesIV** [comment]
> Ping me if I can help in some way.

I appreciate that, thank you.  This might take some time, as I'm trying to determine how certs are generated by pester (and learn pester at the same time)

**Comment by johlju** [comment]
In a unit test you mock cmdlets/functions with Pester. So you mock what a cmdlet should return. So if you have a function let say `Get-Certificate` you mock it to return the certificate (the necessary object with properties). 

Example below. Not sure this is the correct way to mock the certificate in this case but gives you an idea. 

```
Mock -CommandName Get-Certificate -MockWith {
    return [PSCustomObject] @{
        SubjectName = ‘cert1’
        Property2 = ‘value2’
    }
}
```

**Comment by johlju** [comment]
We have renamed the resource, removing 'x', so please rebase this PR.

**Pull request closed without merging**
