### PR TITLE
WebApplication: Ensure class names match for WebApplicationAuthenticationInformation

### PR DESCRIPTION
**Pull request by chelnak**
#### Pull Request (PR) description

Prior to this change there as a mismatch between the class name for `WebApplicationAuthenticationInformation` in the schema and implementation.

The schema referenced the class as `DSC_WebApplicationAuthenticationInformation` whereas the implementation referenced the class as `MSDT_xWebApplicationAuthenticationInformation`.

This caused an error when CIM would later try and lookup the class. The underlying error returned was `MI RESULT 5`.

When consumed by Puppet (via Puppet.Dsc) we see the following:

```
Error: dsc_webapplication: The specified Class does not exist.
Error: /Stage[main]/Main/Dsc_webapplication[TestApp]: Could not evaluate: undefined method `[]' for nil:NilClass
```

This commit resolves the issue by updating the class name passed to `New-CimInstance` so that it matches the value defined in the schema.

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/617)

### CODE REVIEW

**Comment by binford2k** [comment]
@johlju anything else we need to do to get this reviewed and merged?

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/617#-:-NGg95_tEOGBA1RkhNJV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chelnak)

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/617)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chelnak)

**Comment by johlju** [comment]
@chelnak thank you for this change. Will merge as soon as the tests passes again.

**Comment by chelnak** [comment]
Thank you @johlju 🙏

**Comment by chelnak** [comment]
Thanks so much for merging.

What are you release cycles like for resources? Are we likely to see a patch release before Xmas?

**Comment by johlju** [comment]
A preview release should have already been released, it is done automatically when merging to main. The community decides when a full release should be done. But since this PR is fixing an error that is affecting existing configuration to be converted from the ‘x’ module the community should probably release it soon. 

Ping on the Slack #dsc channel (see dsccommunity.org) in a week or so and suggest for the community to release it.

**Comment by chelnak** [comment]
Perfect thank you!

**Pull request merged**
