### PR TITLE
WebConfigPropertyCollection - allow different property collection key types to be added, IisModule / IisMimeTypeMapping - set Ensure as default

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

- Allow WebConfigPropertyCollection to be used to add different key types when there are none already (e.g. to allow https://stackoverflow.com/questions/30135330/managing-iis-net-authorization-rules-with-a-powershell-script)
- Set IisModule, IisMimeTypeMapping to have Ensure = 'Present' by default.

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640)

### CODE REVIEW

**Review by dan-hughes — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640)* status: all files reviewed, 1 unresolved discussion (waiting on @Borgquite)

*[a discussion](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640#-O9o5uHu82FQseUzGNtP:-O9o5uHu82FQseUzGNtQ:b-k3kh37) (no related file):*
Can you update the examples and integration tests to cover the default behaviour? 

For the integration tests do not change them all but some to prove that if Ensure is supplied it works and also when not. 

___

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

*[a discussion](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640#-O9o5uHu82FQseUzGNtP:-O9oo-576t1K9waeV1ap:b-896fix) (no related file):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Can you update the examples and integration tests to cover the default behaviour? 

For the integration tests do not change them all but some to prove that if Ensure is supplied it works and also when not.
</blockquote></details>

Done.

___

**Comment by dan-hughes** [comment]
@johlju

**Comment by Borgquite** [comment]
As always @dan-hughes , @johlju - thank you! :)

**Pull request merged**
