### PR TITLE
MockWebAdministrationWindowsFeature: Make stubs throw StubNotImplemented when invoked

### LINKED ISSUE #351: xWebAdministration: Stubs for unit tests should throw if they are called
When the stubs are called, they are executed and nothing happens. They should instead throw an error saying that Stub was called. This way it is shown that a cmdlet wasn't mocked correctly. If cmdlets are not mocked correctly then when user expecting to run unit tests on a lab it could actually change the system that only an integration test should do. 

All stub functions here:
https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/MockWebAdministrationWindowsFeature.psm1

Should throw something like this.

```
throw '{0}: StubNotImplemented' -f $MyInvocation.MyCommand
```

### PR DESCRIPTION
**Pull request by tommysor**
#### Pull Request (PR) description

- Make stubs throw StubNotImplemented when invoked
- Add Mock for unit tests that called stubs.
~~- Add missing stub Set-ItemProperty.
  Note this stub is missing `HelpUri='xx'`, `Position=0` and similar found on the other stubs.
  *If this should be added*: Is there an easy way to find what those should be?~~

#### This Pull Request (PR) fixes the following issues

Fix #351

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/620)

### CODE REVIEW

**Comment by johlju** [comment]
I will get to this one as soon as I have a chance. Ping me in a week if I forget.

**Comment by tommysor** [comment]
> I will get to this one as soon as I have a chance. Ping me in a week if I forget.

ping @johlju

**Review by johlju — CHANGES_REQUESTED** [review]
Thanks for reminding me. :slightly_smiling_face: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/620#-:-NJ_EzC54kXd1x7f_ruz:b-yxitfc)* status: all files reviewed, 2 unresolved discussions (waiting on @tommysor)

___
*[`tests/MockWebAdministrationWindowsFeature.psm1` line 1846 at r1](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/620#-NJ_EhWZEDMsXDAsWV5b:-NJ_EhWZEDMsXDAsWV5c:bmigmeb) ([raw file](https://github.com/dsccommunity/webadministrationdsc/blob/e47a97ddc30a6140e21492cb2bcc7e68401901f8/tests/MockWebAdministrationWindowsFeature.psm1#L1846)):*
> ```PowerShell
> 
> 
> function Set-ItemProperty {
> ```

This should not be part of this stub module since it is not a command that is part of the original module



_Code quote:_
```PowerShell
function Set-ItemProperty {
```
___
*[`tests/Unit/DSC_Website.Tests.ps1` line 632 at r1](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/620#-NJ_FDHMBSv0NtXrScub:-NJ_FDHMBSv0NtXrScuc:b-newma3) ([raw file](https://github.com/dsccommunity/webadministrationdsc/blob/e47a97ddc30a6140e21492cb2bcc7e68401901f8/tests/Unit/DSC_Website.Tests.ps1#L632)):*
> ```PowerShell
>                 Mock -CommandName Get-Website -MockWith { return $MockWebsite }
> 
>                 Mock -CommandName Get-WebConfiguration -MockWith { $null }
> ```

We don't need this if a mock should not mock any code. We should just leave out `MockWith` entirely. Throughout the test code.



_Suggestion:_
```PowerShell
Mock -CommandName Get-WebConfiguration
```

**Comment by tommysor** [comment]
- Removed mock `Set-ItemProperty`
- Removed `-MockWith { $null }`

I don't know what is happening in the Azure Pipeline.
I'm reasonably sure that's not because of my changes.

```
ERROR: Failed to import classes from file /home/vsts/work/1/s/source/DSCResources/DSC_IisFeatureDelegation/DSC_IisFeatureDelegation.schema.mof. Error Exception calling "ImportClasses" with "3" argument(s): "Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmi: cannot open shared object file: No such file or directory"
At /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.11.1/DscResource.DocGenerator.psm1:1486 char:9
+         throw "Failed to import classes from file $FileName. Error $_ …

```

**Comment by johlju** [comment]
Azure DevOps changed the latest linux build worker and it is no longer handles MOF resources. Please change the below line from `ubuntu-latest` to `windows-latest`.

https://github.com/dsccommunity/WebAdministrationDsc/blob/8bcd584fc92a53a747965bc38e1cd5e76c08da8c/azure-pipelines.yml#L28

**Comment by tommysor** [comment]
- set `vmImage: 'windows-latest'`

Build now passing

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/620#-:-NJjqCBf0zy6XlH5rRlA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tommysor)

**Comment by johlju** [comment]
Thank you for this @tommysor 🙂

**Pull request merged**
